### ISSUE TITLE
compile requirements

### ISSUE THREAD

**Issue by Mike-K8LH** [olivierjan/Variable-Clock#1]
I tried compiling with MPLABX 5.40, DFP 1.2.72, and XC8 2.10 but "no joy" so far.  What am I doing wrong?

![variable clock problem](https://user-images.githubusercontent.com/38607118/103492392-9dd2d400-4df8-11eb-8146-a9db45ea1b1e.jpg)

**Comment by olivierjan** [comment]
Hi, I fixed a typo in one file, compilation is OK now with MPLAB X 5.45 and XC 2.31.
I will do some tests tonight to check it works properly and will clean-up the code a bit.

**Comment by olivierjan** [comment]
Code cleaned up, compiled and tested. Clock output checked with a scope, everything is working as expected now.

**Comment by Mike-K8LH** [comment]
Thank you Sir.  Cheerful regards, Mike, K8LH
